//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "LED_Demo.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include <driverlib/pin_map.h>
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "inc/tm4c123gh6pm.h"

#define count    3333333

//*****************************************************************************
int red;
int blu;

void
PortFunctionInit(void)
{
//	volatile uint32_t ui32Loop;
//		SYSCTL_RCGC2_R = SYSCTL_RCGC2_GPIOF;
//		ui32Loop = SYSCTL_RCGC2_R;
    //
    // Enable Peripheral Clocks 
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF3 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_3);

    //
    // Enable pin PF1 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_1);

    //
    // Enable pin PF2 for GPIOOutput
    //
    GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
		
				GPIO_PORTF_PUR_R |= 0x01; 

}

void GPIOPortF_Handler(void)
{
	GPIO_PORTF_ICR_R |= 0x01;
	red ^= 0x02;
	blu^= 0x04;
	GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1,red);
	GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2,blu);
	
}
void Interrupt_Init(void)
{
	NVIC_EN0_R |= 0x40000000; //Enable Interrupt 30 (GPOIF) on NVIC
	NVIC_PRI7_R &= ~0x00E00000; //Set Priority to 0
	GPIO_PORTF_IM_R |= 0x01; //Enable Interrupt Mask PF0
	GPIO_PORTF_IS_R &= ~0x01; // Clear IS bit for edge trigger on PF0
	GPIO_PORTF_IBE_R |= 0x01; // Enable Both Edge trigger for PF0
	IntMasterEnable();
}

int main(void)
{
	PortFunctionInit();

	Interrupt_Init();
	red = 0x0;
	blu = 0x04;
	
	GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1,red);
	GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2,blu);
	SysCtlDelay(count);
	
	while(1)
	{
			GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1,0x0);
			GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2,0x0);
			SysCtlDelay(count);		
			GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1,red);
			GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2,blu);
			SysCtlDelay(count);
	}		
	
}
